#!/bin/sh

make_attempt () {
	clear
	$EDITOR $XDG_CACHE_HOME/sm/temp.txt
	delta --wrap-max-lines 100 $XDG_CACHE_HOME/sm/temp.txt $XDG_CACHE_HOME/sm/verse.txt
	rm $XDG_CACHE_HOME/sm/temp.txt
}

main () {
	while [[ $confirm != [Qq] ]]; do
		read -p "What do you want to do? [P]ractice? [V]iew the Verse? [Q]uit? " confirm
		if [[ $confirm == [Vv] ]]
		then
			echo -e $VERSE | fold -sw 70 | less --quit-if-one-screen -RX
		elif [[ $confirm == [Qq] ]]
		then
			:
		else
			make_attempt
		fi
	done
	rm $XDG_CACHE_HOME/sm/verse.txt
}

confirm=""
ESV_ENDPOINT="https://api.esv.org/v3/passage/text/?"
ESV_QUERY_ADDONS="include-passage-references=false&include-footnotes=false&include-headings=false&include-short-copyright=false&"
source $XDG_CONFIG_HOME/sm/config

REFERENCE=$(echo $1 | tr " " "+")

VERSE=$(curl -s -H "${API_KEY}" "${ESV_ENDPOINT}${ESV_QUERY_ADDONS}q=$REFERENCE" | jq ".passages|.[0]" | sed "y/’/'/" | sed "y/—/-/")
echo -e ${VERSE} > $XDG_CACHE_HOME/sm/verse.txt

main
