Output demo.gif

Set FontSize 18
Set Width 1200
Set Height 600

Sleep 500ms
Type "scripture_phaser"
Sleep 1000ms
Enter
Sleep 3000ms

Type l
Sleep 800ms
Enter
Sleep 5000ms

Type r
Sleep 800ms
Enter
Sleep 1000ms
Type "Ephesians 2:8-9"
Sleep 1000ms
Enter
Sleep 2000ms

Type v
Sleep 800ms
Enter
Sleep 10000ms

Type p
Sleep 1200ms
Enter
Sleep 1000ms

Type i
Type "For by grace you have been saved. And this is not your own doing, it is the gift of God, not a result of your works, so that no one may boast."
Type ""
Sleep 5000ms
Type ":wq"
Sleep 500ms
Enter
Sleep 12000ms

Type "s"
Sleep 800ms
Enter
Sleep 10000ms
